### ISSUE TITLE
Audio file

### ISSUE THREAD

**Issue by rezatakhshid** [nazmulkazi/dataset_automated_medical_transcription#1]
Hi, can't seem to locate actual audio files. 
Thanks

**Comment by nazmulkazi** [comment]
Sorry, GitHub handles large files differently and requires a premium subscription. I have created an alternate repository only for the audio files and added the link in the readme file (also pasted below).

Alternate repository of audio recordings: [https://oxiago.com/curavoice/dataset/10.5281.4279041/](https://oxiago.com/curavoice/dataset/10.5281.4279041/)

**Comment by rezatakhshid** [comment]
Only if I had read the readme thoroughly 🙈. Thanks for the help.
