### ISSUE TITLE
README lacks information on provenance of the source data.

### ISSUE THREAD

**Issue by jeb-orcl** [nazmulkazi/dataset_automated_medical_transcription#2]
Hi. We would like to use your dataset in some internal R&D work. However, Oracle is adamant about only using data that is appropriately sourced and licensed. The license on this repo is fine, but we are concerned with how your original starting data (the doctor/patient conversations) was sourced. Can you update the README to provide information as to how you obtained these actual conversations, whether there was consent obtained from the patients, and/or what rights you have to release this content?

Thank you.

**Comment by nazmulkazi** [comment]
This research was conducted at Montana State University and the university has access to these transcripts published by Alexander Street Press, check out the _Transcripts adapted from Alexander Street_ section. We didn't collect, record, or transcribe the original interviews. You will need to contact Alexander Street Press for that. We only used the original transcripts to generate data (we had some special requirements) for our study that closely resembles real doctor-patient conversations.
