### ISSUE TITLE
Cannot fetch lfs files

### ISSUE THREAD

**Issue by spacemonqi** [nazmulkazi/dataset_automated_medical_transcription#3]
Running `git lfs fetch` yields 
```
batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.                              
error: failed to fetch some objects from 'https://github.com/nazmulkazi/dataset_automated_medical_transcription.git/info/lfs'
```

**Comment by nazmulkazi** [comment]
Uploading the audio recording vis LFS was a mistake due to the cost associated with it. Please forget about the LFS and use the alternative repository (oxiago.com; this is my private web server) mentioned in the readme to get the audio recordings.
