### ISSUE TITLE
Cannot pull from LFS

### ISSUE THREAD

**Issue by rakesh-clinicyantra** [nazmulkazi/dataset_automated_medical_transcription#5]
Hi,

I am trying to do `git lfs fetch --all` but I am getting this message below. Maybe you need to buy a pack ?

```
➜  dataset_automated_medical_transcription git:(main) ✗ git lfs fetch --all
fetch: 71 objects found, done.
fetch: Fetching all references...
batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.
error: failed to fetch some objects from 'https://github.com/nazmulkazi/dataset_automated_medical_transcription.git/info/lfs'
```

**Comment by rakesh-clinicyantra** [comment]
Maybe you can upload the data using google drive / baidu if you don't want to pay for LFS services.

**Comment by nazmulkazi** [comment]
Please check the readme. I already uploaded the data to an alternate host a long time ago and is available through oxiago.com; do not worry, it is my personal website.
